
== Build and run a Cloudera trial environment in a dockerless container

Based on https://github.com/carrossoni/CDPDCTrial/

----
We'll use 
buildah to create the Cloudera trial environment container and
podman to run it

Buildah is a command-line tool for building Open Container Initiative-compatible 
(that means Docker- and Kubernetes-compatible, too) images quickly and easily. 
Buildah is easy to incorporate into scripts and build pipelines and 
doesn’t require a running container daemon to build its image.
See more at https://opensource.com/article/18/6/getting-started-buildah
----


The buildah script to create the container is at https://github.com/marcredhat/cloudera/blob/master/build.sh


----
Let's have a look at the container created by the script above

sudo buildah containers
#CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
#ed92c18b5b99     *     f142359e2130 registry.centos.org/centos/centos:latest centos-working-container-1
----

----
Commit the container to a new image

sudo buildah commit centos-working-container-1 marccdp
----

----
Publish the container to your favorite registry

sudo podman  login -u="<quay.io user>" -p="<quay.io encrypted password>" quay.io
sudo  podman push localhost/marccdp  quay.io/marcf5/marccdp
----

#sudo podman run  -p 7180:7180 --systemd=true --privileged  -it --name marccdp2 localhost/marccdp:latest /sbin/init
#sudo podman run --systemd=true --privileged  -it --name marccdp localhost/marccdp:latest /sbin/init

#sudo podman ps -a 
#sudo podman exec -it marccdp /bin/bash

#systemctl start cloudera-scm-server

#[root@6de36c33185f /]# find / -name create_cluster.py
#/CDPDCTrial/scripts/create_cluster.py



#su - postgres -c "/usr/pgsql-9.6/bin/initdb --locale en_US.UTF-8 -D '/var/lib/postgres/data'"
#su - postgres -c "/usr/pgsql-9.6/bin/pg_ctl -D /var/lib/postgres/data -l logfile start"

#sudo podman exec -it marccdp /bin/bash

#ss -anpt | grep java | grep LISTEN
#LISTEN     0      50           *:7180                     *:*                   users:(("java",pid=14718,fd=400))
#LISTEN     0      50           *:7182                     *:*                   users:(("java",pid=14718,fd=392))

#systemctl status cloudera-scm-agent
#systemctl status cloudera-scm-server 
#curl -u "admin:admin"  http://127.0.0.1:7180/api/version
#v41
# tail -f /var/log/cloudera-scm-server/cloudera-scm-server.log
